old_sound_rabbit_mq:
  connections:
    default:
      host:     rabbitmq
      port:     5672
      user:     'guest'
      password: 'guest'
      vhost:    '/'
      lazy:     false
      connection_timeout: 3
      read_write_timeout: 3
      keepalive: false
      heartbeat: 0
      use_socket: true
  producers:
    send_payment:
      connection:       default
      exchange_options: { name: 'notification.v1.send_payment', type: direct }

  consumers:
    send_payment:
      connection:       default
      exchange_options: { name: 'notification.v1.send_payment', type: direct }
      queue_options:    { name: 'notification.v1.send_payment' }
      callback:         app.consumer.payment_sender